name: Rust

on:
  push:
    branches: ["main"]
    tags: ["v*"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA1 to build"
        required: false
        default: "HEAD"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: cargo build --release

      - name: Build workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git checkout ${{ github.event.inputs.commit_sha }}
          cargo build --release

      - name: Get commit SHA of current build
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: tacky-borders-${{ env.COMMIT_SHA }}
          path: target/release/*.exe
          retention-days: 30

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run tests
        run: cargo test --verbose

  release:
    needs: build
    runs-on: windows-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts/

      - name: Compress artifacts
        run: |
          $compress = @{
            Path = "./artifacts/tacky-borders.exe"
            DestinationPath = "./artifacts/tacky-borders-${{ github.ref_name }}.zip"
          }
          Compress-Archive @compress
          Remove-Item -Path "./artifacts/tacky-borders.exe"

      - name: Generate checksums
        run: |
          cd ./artifacts
          sha256sum * > sha256sums.txt
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./artifacts/*
